spring.application.name=ad-click-aggregator
server.port=8086

# ===============================
# DATASOURCE (ClickHouse)
# ===============================
spring.datasource.url=jdbc:clickhouse://localhost:8123/default
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
spring.datasource.username=default
spring.datasource.password=click@house879

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=ad-clicks-group-2
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Listener
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=3
spring.kafka.listener.idle-event-interval=10000

# Producer (for test endpoint)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ===============================
# FLINK KAFKA (used by FlinkJobRunner — runs inside Docker)
# Use Docker container names, NOT localhost
# ===============================
kafka.bootstrap.servers=broker:9092
kafka.topic=ad-click-topic-1
kafka.group.id=flink-ad-clicks-group

# ===============================
# FLINK CLUSTER (Docker)
# ===============================
flink.rest.url=http://localhost:8087
flink.job.jar-path=target/flink-job.jar

# ClickHouse address for Flink (inside Docker)
flink.clickhouse.url=jdbc:clickhouse://clickhouse:8123/default
flink.clickhouse.user=default
flink.clickhouse.password=click@house879

# ===============================
# PERFORMANCE TUNING (Optional)
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true